title: Emily Khor # your name (or website title) here
logo: "/images/profile.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Hey there, I'm Emily - a systems engineer turned aspiring data scientist. Welcome to my data science portfolio. 
  Through my portfolio, I aim to showcase my ability to use machine learning tools to extract insights from data and present them through impactful visualization.
  <br>
  <blockquote> 
    “Practice isn't the thing you do once you're good. It's the thing you do that makes you good."
    <br>
    <small><sub>― Malcolm Gladwell, Outliers: The Story of Success”</sub></small>
  </blockquote>
  <br>
  <p>
  <a href="https://www.linkedin.com/in/emilyelk/"><img src="https://img.shields.io/badge/-LinkedIn-white?logo=linkedin&style=social" alt=""></a>
  <a href="https://github.com/MK-ek11?tab=repositories"><img src="https://img.shields.io/badge/-GitHub-white?logo=github&amp;style=social" alt=""></a>
  <a href="https://public.tableau.com/app/profile/em.k"><img src="https://img.shields.io/badge/-Tableau-white?logo=tableau&style=social" alt=""></a>
  </p>
  
theme: jekyll-theme-minimal

colors:
  crimson: '#900C3F'
